Web/NurserySchoolWebPortal.Web/Areas/Administration/Controllers/ChildrenController.cs
namespace NurserySchoolWebPortal.Web.Areas.Administration.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using NurserySchoolWebPortal.Data.Common.Repositories;
    using NurserySchoolWebPortal.Data.Models;
    using NurserySchoolWebPortal.Services.Data;
    using NurserySchoolWebPortal.Web.ViewModels.Children;

    public class ChildrenController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Child> childrenRepository;
        private readonly IDeletableEntityRepository<ApplicationUser> usersRepository;
        private readonly IGroupsService groupsService;
        private readonly ISchoolsService schoolsService;
        private readonly IChildrenService childrenService;

        public ChildrenController(
            IDeletableEntityRepository<Child> childrenRepository,
            IDeletableEntityRepository<ApplicationUser> usersRepository,
            IGroupsService groupsService,
            ISchoolsService schoolsService,
            IChildrenService childrenService)
        {
            this.childrenRepository = childrenRepository;
            this.usersRepository = usersRepository;
            this.groupsService = groupsService;
            this.schoolsService = schoolsService;
            this.childrenService = childrenService;
        }

        public IActionResult Index()
        {
            var children = this.childrenRepository.AllAsNoTrackingWithDeleted()
                .Select(x => new ChildViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    MiddleName = x.MiddleName,
                    LastName = x.LastName,
                    CreatedOn = x.CreatedOn,
                    ModifiedOn = (System.DateTime)x.ModifiedOn,
                    IsDeleted = x.IsDeleted,
                    DeletedOn = (System.DateTime)x.DeletedOn,
                })
                .ToList();

            var viewModel = new ChildrenViewModel
            {
                Children = children,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var childViewModel = await this.childrenRepository.All()
                .Where(x => x.Id == id)
                .Select(x => new ChildViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    MiddleName = x.MiddleName,
                    LastName = x.LastName,
                    Gender = (int)x.Gender,
                    GroupName = x.NurseryGroup.Name,
                    NurseryGroup = x.NurseryGroupId,
                    SchoolName = x.NurseryGroup.NurserySchool.Name,
                    NurserySchool = x.NurseryGroup.NurserySchoolId,
                    DateOfBirth = x.DateOfBirth.ToShortDateString(),
                    EGN = x.EGN,
                    Address = x.Address,
                    ParentName = x.Parent.User.FirstName + " " + x.Parent.User.LastName,
                    ParentId = x.Parent.Id,
                    PhoneNumber = x.Parent.User.PhoneNumber,
                    CreatedOn = x.CreatedOn,
                    ModifiedOn = (DateTime)x.ModifiedOn,
                    DeletedOn = (DateTime)x.DeletedOn,
                    IsDeleted = x.IsDeleted,
                })
                .FirstOrDefaultAsync();

            if (childViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(childViewModel);
        }

        public IActionResult Create()
        {
            var viewModel = new ChildInputModel();
            viewModel.GroupsItems = this.groupsService.GetAllAsKeyValuePairs();
            viewModel.SchoolsItems = this.schoolsService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChildInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.childrenService.AddAsync(input);

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var childViewModel = this.childrenRepository.All()
                .Where(x => x.Id == id)
                .Select(x => new ChildInputModel
                {
                    FirstName = x.FirstName,
                    MiddleName = x.MiddleName,
                    LastName = x.LastName,
                    Address = x.Address,
                    NurseryGroup = x.NurseryGroupId,
                    Parent = x.Parent.Id,
                    ParentName = x.Parent.User.FirstName + " " + x.Parent.User.LastName,
                    PhoneNumber = x.Parent.User.PhoneNumber,
                    CreatedOn = x.CreatedOn,
                    ModifiedOn = (DateTime)x.ModifiedOn,
                    DeletedOn = (DateTime)x.DeletedOn,
                    IsDeleted = x.IsDeleted,
                })
                .FirstOrDefault();

            childViewModel.GroupsItems = this.groupsService.GetAllAsKeyValuePairs();

            if (childViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(childViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ChildInputModel input)
        {
            var currentChild = this.childrenRepository.AllAsNoTracking()
                .FirstOrDefault(x => x.Id == id);

            var groupId = input.GroupName == null ? currentChild.NurseryGroupId
                                                        : int.Parse(input.GroupName);

            var child = new Child
            {
                Id = input.Id,
                FirstName = input.FirstName,
                MiddleName = input.MiddleName,
                LastName = input.LastName,
                Address = input.Address,
                IsDeleted = currentChild.IsDeleted,
                DeletedOn = currentChild.DeletedOn,
                CreatedOn = currentChild.CreatedOn,
                ModifiedOn = input.ModifiedOn,
                NurseryGroupId = groupId,
                DateOfBirth = currentChild.DateOfBirth,
                EGN = currentChild.EGN,
                Gender = currentChild.Gender,
            };

            if (id != child.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.childrenRepository.Update(child);
                    await this.childrenRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.ChildExists(child.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(child);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var childViewModel = await this.childrenRepository.All()
                .Where(x => x.Id == id)
                .Select(x => new ChildViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    MiddleName = x.MiddleName,
                    LastName = x.LastName,
                    GroupName = x.NurseryGroup.Name,
                    SchoolName = x.NurseryGroup.NurserySchool.Name,
                    DateOfBirth = x.DateOfBirth.ToShortDateString(),
                    EGN = x.EGN,
                    Address = x.Address,
                    ParentName = x.Parent.User.FirstName + " " + x.Parent.User.LastName,
                    PhoneNumber = x.Parent.User.PhoneNumber,
                    CreatedOn = x.CreatedOn,
                    ModifiedOn = (DateTime)x.ModifiedOn,
                    DeletedOn = (DateTime)x.DeletedOn,
                    IsDeleted = x.IsDeleted,
                })
                .FirstOrDefaultAsync();

            if (childViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(childViewModel);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var child = this.childrenRepository.All().FirstOrDefault(x => x.Id == id);
            this.childrenRepository.Delete(child);
            await this.childrenRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool ChildExists(int id)
        {
            return this.childrenRepository.All().Any(x => x.Id == id);
        }
    }
}

Web/NurserySchoolWebPortal.Web/Controllers/FeesController.cs
namespace NurserySchoolWebPortal.Web.Controllers
{

    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NurserySchoolWebPortal.Common;
    using NurserySchoolWebPortal.Data.Common.Repositories;
    using NurserySchoolWebPortal.Data.Models;
    using NurserySchoolWebPortal.Services.Data;
    using NurserySchoolWebPortal.Web.ViewModels.Fees;

    [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
    public class FeesController : BaseController
    {
        private readonly IDeletableEntityRepository<Principal> principalsRepository;
        private readonly IChildrenService childrenService;
        private readonly IFeesService feesService;

        public FeesController(
            IDeletableEntityRepository<Principal> principalsRepository,
            IChildrenService childrenService,
            IFeesService feesService)
        {
            this.principalsRepository = principalsRepository;
            this.childrenService = childrenService;
            this.feesService = feesService;
        }

        public IActionResult Create()
        {
            var viewModel = new FeeInputModel();
            var userName = this.User.Identity.Name;
            var currentPrincipal = this.principalsRepository.AllAsNoTracking()
                .FirstOrDefault(x => x.User.UserName == userName);
            var schoolId = currentPrincipal.NurserySchoolId;
            viewModel.ChildrenItems = this.childrenService.GetAllAsKeyValuePairsPerSchool(schoolId);

            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FeeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.feesService.AddAsync(input);

            return this.RedirectToAction("AllPerSchool", "Children", new { area = string.Empty });
        }
    }
}

Web/NurserySchoolWebPortal.Web/Controllers/PersonalInfosController.cs
namespace NurserySchoolWebPortal.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using NurserySchoolWebPortal.Common;
    using NurserySchoolWebPortal.Data.Common.Repositories;
    using NurserySchoolWebPortal.Data.Models;
    using NurserySchoolWebPortal.Services.Data;
    using NurserySchoolWebPortal.Web.ViewModels.PersoonalInfo;

    [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
    public class PersonalInfosController : BaseController
    {
        private readonly IDeletableEntityRepository<Principal> principalsRepository;
        private readonly IDeletableEntityRepository<PersonalInfo> personalInfosRepository;
        private readonly IChildrenService childrenService;
        private readonly IPersonalInfosService personalInfosService;

        public PersonalInfosController(
            IDeletableEntityRepository<Principal> principalsRepository,
            IDeletableEntityRepository<PersonalInfo> personalInfosRepository,
            IChildrenService childrenService,
            IPersonalInfosService personalInfosService)
        {
            this.principalsRepository = principalsRepository;
            this.personalInfosRepository = personalInfosRepository;
            this.childrenService = childrenService;
            this.personalInfosService = personalInfosService;
        }

        public IActionResult Create()
        {
            var viewModel = new PersonalInfoInputModel();
            var userName = this.User.Identity.Name;
            var currentPrincipal = this.principalsRepository.AllAsNoTracking()
                .FirstOrDefault(x => x.User.UserName == userName);
            var schoolId = currentPrincipal.NurserySchoolId;
            viewModel.ChildrenItems = this.childrenService.GetAllAsKeyValuePairsPerSchool(schoolId);

            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonalInfoInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.personalInfosService.AddAsync(input);

            return this.RedirectToAction("AllPerSchool", "Children", new { area = string.Empty });
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var personalInfoViewModel = this.personalInfosService.GetById((int)id);

            if (personalInfoViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(personalInfoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PersonalInfoInputModel input)
        {
            var currentPersonalInfo = this.personalInfosRepository.AllAsNoTracking()
                .FirstOrDefault(x => x.ChildId == id);

            var personalInfo = new PersonalInfo
            {
                Id = currentPersonalInfo.Id,
                Height = input.Height,
                Weight = input.Weight,
                ChildId = currentPersonalInfo.ChildId,
                IsDeleted = currentPersonalInfo.IsDeleted,
                DeletedOn = currentPersonalInfo.DeletedOn,
                CreatedOn = currentPersonalInfo.CreatedOn,
                ModifiedOn = input.ModifiedOn,
            };

            if (id != personalInfo.ChildId)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.personalInfosRepository.Update(personalInfo);
                    await this.personalInfosRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.PersonalInfoExists(personalInfo.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction("AllPerSchool", "Children", new { area = string.Empty });
            }

            return this.View(personalInfo);
        }

        private bool PersonalInfoExists(int id)
        {
            return this.personalInfosRepository.All().Any(x => x.Id == id);
        }
    }
}

Web/NurserySchoolWebPortal.Web/Views/Children/AllPerSchool.cshtml
@model NurserySchoolWebPortal.Web.ViewModels.Children.ChildrenViewModel
@{
    ViewData["Title"] = "Index";
    DateTime.TryParse("01.01.0001 г. 00:00:00                ", out var date);
}
<h1>Children List</h1>
<table id="DataTable" class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>IsDeleted</th>
            <th>CreatedOn</th>
            <th>ModifiedOn</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var child in this.Model.Children)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => child.FirstName) @Html.DisplayFor(modelItem => child.MiddleName) @Html.DisplayFor(modelItem => child.LastName)
            </td>
            @if (child.DeletedOn == date)
            {
                <td></td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => child.IsDeleted)
                    @Html.DisplayFor(modelItem => child.DeletedOn)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => child.CreatedOn)
            </td>
            @if (child.ModifiedOn == date)
            {
                <td></td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => child.ModifiedOn)
                </td>
            }
            @if (!child.IsDeleted)
            {
        <td>
            <a asp-controller="PersonalInfos" asp-action="Create">Add Info</a> |
            <a asp-controller="PersonalInfos" asp-action="Edit" asp-route-id="@child.Id">Edit Info</a> |
            <a asp-controller="Fees" asp-action="Create">Add Fee</a> |
            <a asp-controller="Fees" asp-action="Edit" asp-route-id="@child.Id">Edit Fee</a>
        </td>

            }
        </tr>
    }
     </tbody>
 </table>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#DataTable').DataTable();
        });
    </script>
}

Web/NurserySchoolWebPortal.Web/Views/Children/ById.cshtml
@model NurserySchoolWebPortal.Web.ViewModels.Children.ChildViewModel

<link href="~/css/child.css" rel="stylesheet">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    @if (Model.Gender == 1)
                    {
                        <img src="https://image.shutterstock.com/image-illustration/cartoon-character-little-boy-points-260nw-1550040197.jpg" alt="boy pic" />
                    }
                    else if (Model.Gender == 2)
                    {
                        <img src="https://image.shutterstock.com/image-vector/happy-african-american-girl-cartoon-260nw-522003124.jpg" alt="girl pic" />
                    }
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        @Model.FirstName @Model.MiddleName @Model.LastName
                    </h5>
                    <h6>
                        @Model.SchoolName Nursery School
                    </h6>
                    <p class="proile-rating">STARS : <span>8/10</span></p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Personal Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#pr" role="tab" aria-controls="pr" aria-selected="false">Fees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>Parent Info</p>
                    <a href="">@Model.ParentName</a><br />
                    <a href="">@Model.Email</a><br />
                    <a href="">@Model.PhoneNumber</a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>First Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.FirstName</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Middle Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.MiddleName</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Last Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.LastName</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Date of Birth</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.DateOfBirth</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Address</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Address</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nursery School</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.SchoolName</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nursery Group</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.GroupName</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Height(cm)</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Height</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Weight(kg)</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Weight</p>
                            </div>
                        </div>
                        @*<div class="row">
                            <div class="col-md-6">
                                <label>Immunizations</label>
                            </div>
                            foreach (var immunization in Model.PersonalInfo.Immunizations)
                            {
                            <div class="col-md-6">
                                <p>Model.PersonalInfo.Immunizations.Name-Model.PersonalInfo.Immunizations.Date</p>
                            </div>
                            }
                        </div>*@
                    </div>
                    <div class="tab-pane fade" id="pr" role="tabpanel" aria-labelledby="pr-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Title</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.FeeTitle</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>From</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.FeeDateFrom</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>To</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.FeeDateTo</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Fee</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.FeeMoneyAmount</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>