Web/NurserySchoolWebPortal.Web/Controllers/ImagesController.cs
namespace NurserySchoolWebPortal.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using NurserySchoolWebPortal.Common;
    using NurserySchoolWebPortal.Data;
    using NurserySchoolWebPortal.Data.Common.Repositories;
    using NurserySchoolWebPortal.Data.Models;
    using NurserySchoolWebPortal.Services.Data;
    using NurserySchoolWebPortal.Web.ViewModels.Images;

    public class ImagesController : BaseController
    {
        private readonly ApplicationDbContext dbContext;
        private readonly IImagesService imagesService;
        private readonly IGroupsService groupsService;
        private readonly IDeletableEntityRepository<Image> imagesRepository;

        public ImagesController(
            ApplicationDbContext dbContext,
            IImagesService imagesService,
            IGroupsService groupsService,
            IDeletableEntityRepository<Image> imagesRepository)
        {
            this.dbContext = dbContext;
            this.imagesService = imagesService;
            this.groupsService = groupsService;
            this.imagesRepository = imagesRepository;
        }

        [Authorize(Roles = GlobalConstants.ParentRoleName)]
        public IActionResult AllPerGroup(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            string userName = this.User.Identity.Name;
            var currentUser = this.dbContext.Parents.Include(x => x.Children).FirstOrDefault(x => x.User.Email == userName);
            var child = currentUser.Children.FirstOrDefault();
            var groupId = child.NurseryGroupId;
            var school = this.dbContext.NurserySchools.FirstOrDefault(x => x.NurseryGroups.Any(x => x.Id == groupId));

            const int ImagesPerPage = 6;

            var viewModel = new ImagesListViewModel
            {
                ItemsPerPage = ImagesPerPage,
                PageNumber = id,
                ItemsCount = this.imagesService.GetCount(groupId),
                Images = this.imagesService.AllPerGroup(groupId, id, ImagesPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult AllPerSchool(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            string userName = this.User.Identity.Name;
            var currentPrincipal = this.dbContext.Principals
                .FirstOrDefault(x => x.User.UserName == userName);
            var schoolId = currentPrincipal.NurserySchoolId;

            const int ImagesPerPage = 6;

            var viewModel = new ImagesListViewModel
            {
                ItemsPerPage = ImagesPerPage,
                PageNumber = id,
                ItemsCount = this.imagesService.GetCountPerSchool(schoolId),
                Images = this.imagesService.AllPerSchool(schoolId, id, ImagesPerPage),
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
        public IActionResult Create()
        {
            var viewModel = new ImageInputModel();
            var userName = this.User.Identity.Name;
            var currentPrincipal = this.dbContext.Principals
                .FirstOrDefault(x => x.User.UserName == userName);
            var schoolId = currentPrincipal.NurserySchoolId;
            viewModel.GroupsItems = this.groupsService.GetAllAsKeyValuePairsPerSchool(schoolId);

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ImageInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.imagesService.AddAsync(input);

            return this.RedirectToAction(nameof(this.AllPerSchool));
        }

        [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var image = await this.imagesRepository.All()
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            return this.View(image);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.PrincipalRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            var image = this.imagesRepository.All().FirstOrDefault(x => x.Id == id);
            this.imagesRepository.Delete(image);
            await this.imagesRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.AllPerSchool));
        }
    }
}

Web/NurserySchoolWebPortal.Web/Views/Images/AllPerGroup.cshtml
@model NurserySchoolWebPortal.Web.ViewModels.Images.ImagesListViewModel

<link href="~/css/img.css" rel="stylesheet" asp-append-version="true" />

<!-- Images -->

<hr />
<div class="row">
    <div id="mdb-lightbox-ui"></div>
    @foreach (var image in this.Model.Images.Images)
    {
        <figure class="media col-md-4">
            <a href=@image.Url data-size="1600x1067">
                <img alt="picture" src=@image.Url class="img-fluid">
            </a>
        </figure>
    }
</div>

<hr />
<!-- Images -->
<partial name="_ImagesPagingPartial" model="Model"/>

Web/NurserySchoolWebPortal.Web/Views/Images/AllPerSchool.cshtml
@model NurserySchoolWebPortal.Web.ViewModels.Images.ImagesListViewModel

<link href="~/css/img.css" rel="stylesheet" asp-append-version="true" />

<!-- Images -->

<hr />
<div class="row">
    <div id="mdb-lightbox-ui"></div>
    @foreach (var image in this.Model.Images.Images)
    {
        <figure class="media col-md-3">
            <a href=@image.Url data-size="1600x1067">
                <img alt="picture" src=@image.Url class="img-fluid">
            </a>
        </figure>
        <hr />
        <a asp-controller="Images" asp-action="Delete" asp-route-id="@image.Id">Delete</a>
    }
</div>

<hr />
<!-- Images -->
<partial name="_ImagesPagingPartialPerSchool" model="Model"/>

Web/NurserySchoolWebPortal.Web/Views/Images/Create.cshtml
@model NurserySchoolWebPortal.Web.ViewModels.Images.ImageInputModel

@{
    ViewData["Title"] = "Create";
    var GroupsItems = this.Model.GroupsItems.Select(x => new SelectListItem(x.Value, x.Key.ToString()));
}

<h1>Create</h1>

<h4>Image</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Extension" class="control-label"></label>
                <input asp-for="Extension" class="form-control" />
                <span asp-validation-for="Extension" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <select asp-for="Group" class="form-control" asp-items="GroupsItems"></select>
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllPerSchool">Back to Images</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/NurserySchoolWebPortal.Web/Views/Images/Delete.cshtml
@model NurserySchoolWebPortal.Data.Models.Image

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h4>Are you sure you want to delete this image?</h4>

<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="AllPerSchool">Back to Images</a>
    </form>
</div>